version: '3.4'
services:
  csharp:
    #docker run -it -v ${PWD}:/work -w /work -p 5001:5001 danidevdock/csharp:1.0.0 /bin/sh
    container_name: csharp_CleanArch
    build:
      context: .
      dockerfile: Dockerfile
      target: debug
      network: host
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - ./src/:/work
    ports:
      - 7004:7004
      - 7002:7002
    depends_on:
      - mssql_azure

  mssql_azure:
    container_name: mssql_azure_cqrs
    image: mcr.microsoft.com/azure-sql-edge:latest
    build:
      network: host
    volumes:
      - ./dbSqlServerAzure/:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Sql_Server123
